# Site settings
title: Inconnito3000
description: Inconnito3000 programs 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Inconnito3000
user_description: 
user_title: Simple Programmer
email: Inconnito3000@gmail.com
#twitter_username: lorem_ipsum
github_username: Inconnito3000
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
